# Generated by Django 2.1.1 on 2018-09-25 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=255, verbose_name='product')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date')),
                ('price', models.FloatField(default=0.0, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='title')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='description')),
                ('navi_address', models.IntegerField(default=0, verbose_name='navi_address')),
                ('address', models.CharField(default='', max_length=255, verbose_name='title')),
                ('phone', models.CharField(default='', max_length=255, verbose_name='title')),
                ('categories', models.ManyToManyField(to='AnyPlaceRest.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', max_length=255, unique=True, verbose_name='login')),
                ('password', models.CharField(default='', max_length=255, verbose_name='password')),
                ('phone', models.CharField(default='', max_length=255, null=True, verbose_name='phone')),
                ('passport', models.CharField(default='', max_length=255, null=True, verbose_name='passport')),
                ('passport_photo', models.ImageField(null=True, upload_to='AnyPlaceRest/passport_photos', verbose_name='passport_photo')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer_id', to='AnyPlaceRest.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_id', to='AnyPlaceRest.Category'),
        ),
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_id', to='AnyPlaceRest.Place'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_id', to='AnyPlaceRest.User'),
        ),
    ]
