# Generated by Django 2.1.1 on 2018-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnyPlaceRest', '0002_auto_20180925_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_url',
            field=models.CharField(default='', max_length=255, verbose_name='product_url'),
        ),
    ]
