# Generated by Django 2.1.1 on 2018-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnyPlaceRest', '0003_order_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_frequency',
            field=models.IntegerField(default=0, verbose_name='send_frequency'),
        ),
    ]
