# Generated by Django 2.1.1 on 2018-09-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnyPlaceRest', '0006_auto_20180926_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='naviaddress',
            name='description',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='naviaddress',
            name='name',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='naviaddress',
            name='address_type',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='address_type'),
        ),
        migrations.AlterField(
            model_name='naviaddress',
            name='default_lang',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='default_lang'),
        ),
        migrations.AlterField(
            model_name='naviaddress',
            name='lat',
            field=models.FloatField(default='', max_length=255, null=True, verbose_name='lat'),
        ),
        migrations.AlterField(
            model_name='naviaddress',
            name='lng',
            field=models.FloatField(default='', max_length=255, null=True, verbose_name='lng'),
        ),
        migrations.AlterField(
            model_name='naviaddress',
            name='map_visibility',
            field=models.BooleanField(default=True, null=True, verbose_name='map_visibility'),
        ),
        migrations.AlterField(
            model_name='naviaddress',
            name='postal_address',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='postal_address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='navi_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AnyPlaceRest.NaviAddress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='navi_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AnyPlaceRest.NaviAddress'),
        ),
    ]
