# Generated by Django 2.1.1 on 2018-09-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnyPlaceRest', '0009_auto_20180927_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='acceptance_date',
            field=models.DateTimeField(auto_now=True, verbose_name='acceptance_date'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(auto_now=True, verbose_name='delivery_date'),
        ),
    ]
