# Generated by Django 2.1.1 on 2018-09-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnyPlaceRest', '0010_auto_20180927_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0, verbose_name='status'),
        ),
    ]
