# Generated by Django 2.1.1 on 2018-09-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnyPlaceRest', '0011_auto_20180927_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fio',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='fio'),
        ),
    ]
